### ISSUE TITLE
Support for torchvision>=0.10.0

### ISSUE THREAD

**Issue by sofroniewn** [conda-forge/torchvision-feedstock#29]
Hello, I was wondering if there are any plans to update the torchvision feedstock to >=0.10.0 (right now it is at 0.9.1).

I know there has been a lot of work around getting pytorch into conda-forge already so I appreciate the effort that's already been done here.

The reason for my request is that I've installed `pytorch` from [conda-forge](https://anaconda.org/conda-forge/pytorch) which installs torch 1.9.0 and I want to use torchvision with it, but if you look at the compatibility matrix for torchvision here https://github.com/pytorch/vision#installation you see that `torch 1.9.0` ==> `torchvision 0.10.0`.

In slightly more detail, I ran

```
conda install -c conda-forge pytorch
conda install -c conda-forge torchvision
```

But when I now run my code I get

```
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.
```

which is explained by the `0.10.0` requirement I mentioned above.

Thanks again for all the hard work getting this far with pytorch in conda-forge!!

**Comment by h-vetinari** [comment]
Hey, it's not too far away. We're basically waiting for the GPU pytorch builds to be uploaded (pytorch is a beast to build and doesn't fit in the 6h timeout on azure, which is why it needs very laborious manual work), then the rest should go smoothly (🤞): https://github.com/conda-forge/pytorch-cpu-feedstock/issues/52

**Comment by hmaarrfk** [comment]
There have been some troubles pinning the ABI. We are trying to address them. For now, we ask that you pin yourself, both pytorch and torchvision.

**Comment by sofroniewn** [comment]
> Hey, it's not too far away.

Ok great! Thanks for the update

> we ask that you pin yourself, both pytorch and torchvision.

Unfortunately the 3rd party code that I'm trying to use requires torch >= 1.9.0, so I'll have to wait.

Thanks again for all the hard work here, it's appreciated!!

**Comment by sofroniewn** [comment]
torchvision >= 0.10.0 is now available and working for me from conda-forge, everything's working great so far. thanks very much!!
