### ISSUE TITLE
osx builds failed

### ISSUE THREAD

**Issue by ngam** [conda-forge/torchvision-feedstock#38]
```
=========================== short test summary info ============================
FAILED test/test_transforms.py::test_randomperspective_fill[L] - assert (255,...
FAILED test/test_transforms.py::test_randomperspective_fill[RGB] - assert (25...
FAILED test/test_transforms.py::test_randomperspective_fill[F] - assert (255....
= 3 failed, 16890 passed, 15458 skipped, 240 deselected, 56 xfailed, 599321 warnings in 929.52s (0:15:29) =
Tests failed for torchvision-0.11.2-py38h992ef89_1_cpu.tar.bz2 - moving package to /Users/runner/miniforge3/conda-bld/broken
WARNING:conda_build.build:Tests failed for torchvision-0.11.2-py38h992ef89_1_cpu.tar.bz2 - moving package to /Users/runner/miniforge3/conda-bld/broken
WARNING conda_build.build:tests_failed(2970): Tests failed for torchvision-0.11.2-py38h992ef89_1_cpu.tar.bz2 - moving package to /Users/runner/miniforge3/conda-bld/broken
TESTS FAILED: torchvision-0.11.2-py38h992ef89_1_cpu.tar.bz2
#
```

https://github.com/conda-forge/torchvision-feedstock/commit/c3c0b29011b098e2fa864840848ee42febff46bf

https://github.com/conda-forge/torchvision-feedstock/runs/4913224109

---

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by hmaarrfk** [comment]
Thanks for monitoring, but I restared the builds to ensure that some linux  builds passed.

The OSX ones were succesful on the first round
![image](https://user-images.githubusercontent.com/90008/150694219-e61baac2-1ef0-4dce-aa42-1b982b87a68a.png)

We can add these to the skip list.

**Comment by ngam** [comment]
Not sure if this related: https://github.com/conda-forge/torchvision-feedstock/pull/37

**Comment by ngam** [comment]
Thanks @hmaarrfk just keeping an eye and help out where I could. Btw, I was trying to find the place where you were talking about aarch64 builds --- I think I can run those locally relatively fast so I am happy to help out. Maybe it was in the pytorch feedstock

**Comment by hmaarrfk** [comment]
yeah, i'm not sure about aarch builds. I probably mentionned it in a few locations. I think the new thing now is trying to cross compile on azure.

**Comment by ngam** [comment]
Through multipass.run, that is, on an M1 machine. Closing this for now since you're on it :)

**Comment by ngam** [comment]
> yeah, i'm not sure about aarch builds. I probably mentionned it in a few locations. I think the new thing now is trying to cross compile on azure.

Ah, I see. I think that would be a good idea. I am not sure why we have a 6-hour limit anyway. Maybe we can use the aarch github VMs? I have no idea what goes into these considerations.
