### ISSUE TITLE
Update to torchvision 0.14.1

### ISSUE THREAD

**Issue by anjos** [conda-forge/torchvision-feedstock#61]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

There is a minor release of PyTorch to 1.12.1, which is available in conda-forge.  However, the torchvision equivalent of this package is not - i.e. 0.13.1.  Could you please consider upgrading this package so that they are properly synchronised?

### Installed packages

```shell
not applicable
```

### Environment info

```shell
not applicable
```

**Comment by anjos** [comment]
@amayoraz ping

**Comment by anjos** [comment]
Same bug, old problem: there is a new conda-forge package for PyTorch 1.13.1. However, that is incompatible with torchvision 0.14.0.   Is a bump to 0.14.1 envisageable?

**Comment by anjos** [comment]
I wonder why this package is not auto-bumped by the bot when a new release bumps on PyPI...

**Comment by h-vetinari** [comment]
Since pytorch doesn't have a stable ABI even between patch versions, we have to recompile everything for 1.13.1. you can open a PR like https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3826

**Comment by h-vetinari** [comment]
This is irrespective of whether we build torchvision 0.14.0 or 0.14.1

**Comment by h-vetinari** [comment]
> I wonder why this package is not auto-bumped by the bot when a new release bumps on PyPI

You can see this under https://conda-forge.org/status/#version_updates. It seems that at some point, a corrupted version tag (`5996`) got pushed to github, and the bot "remembers" this one, and now waits for a version that exceeds that.

This is pretty annoying, but can be solved by manually removing that metadata from the bot history, e.g. like https://github.com/regro/cf-graph-countyfair/pull/34

**Comment by anjos** [comment]
It also states:

> We also found the following errors:
> - could not hash URL template 'https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz'

Is this URL not bot friendly?

**Comment by h-vetinari** [comment]
That's a red herring, it's the false tag that's the problem (there's no URL for a tag with 5996 or a larger version)

**Comment by anjos** [comment]
Right - I submitted the above PR to try and fix the auto-version-bump for torchvision.  Hopefully, there will be PRs sent here automatically when the version bumps.  Concerning the other PR, to actually trigger the bump manually, https://github.com/conda-forge/conda-forge-pinning-feedstock, can't we just wait after the PR above?

**Comment by h-vetinari** [comment]
Closed by #66

**Comment by h-vetinari** [comment]
Thanks for submitting the PR to fix the bot @anjos!

**Comment by anjos** [comment]
Thank you for the reactive work on this.  Seems to be working better now!
