### ISSUE TITLE
torchvision 0.2.2 not available (even via broken channel)

### ISSUE THREAD

**Issue by skroon** [conda-forge/torchvision-feedstock#69]
### Comment:

(I asked this originally at [this issue](https://github.com/pytorch/vision/issues/4665), and was referred here by a response confirming that the relevant version seems to be missing.)

I'm trying to install `torchvision=0.2.2=py_3` to build a reproduction of an environment we have been using, but I now get a `ResolvePackageNotFound` error. The 0.2.2 binaries do not appear to be on conda-forge : they are not listed at https://anaconda.org/conda-forge/torchvision/files?page=10 , and they do not appear when I choose the broken label either.  The `ResolvePackageNotFound` error also persists when I include `conda-forge/label/broken` in the channels for the `environment.yml`.

Does anyone here have more information on why this version is not available, or how it can be installed?

**Comment by skroon** [comment]
The package version is listed under the dependencies section of the `environment.yml` file, and the channels specified are:

```
channels:
  - pytorch
  - ostrokach-forge
  - nvidia
  - conda-forge
  - defaults
```

pypi has yanked `torchvision 0.2.2`, but torchvision isn't specified in the pip section of the `environment.yml` file, so this shouldn't be causing the problem, as I understand it.

**Comment by hmaarrfk** [comment]
Given the information I linked to above. It is really unlikely that any package called torchvision 0.2.2 was ever created at conda-forge.

If you need any more help, please provide a minimum complete reproducer

This blog post may help
https://matthewrocklin.com/minimal-bug-reports#minimal-complete-verifiable-examples

**Comment by skroon** [comment]
This [Dockerfile](https://github.com/conda-forge/torchvision-feedstock/files/11052427/Dockerfile-minimum.txt) and [environment specification](https://github.com/conda-forge/torchvision-feedstock/files/11052428/environment-mini.yml.txt) are a minimum complete reproducer. (Unfortunately I needed to add a .txt extension to  the files to upload them through the issue tracker interface.)

Output of two sessions using them failing on 2 different machines: [session.txt](https://github.com/conda-forge/torchvision-feedstock/files/11052410/session.txt) ; [session2.txt](https://github.com/conda-forge/torchvision-feedstock/files/11052411/session2.txt)

I have verified that the pytorch channel also does not have torchvision 0.2.2 either.  The ostrokach-forge and nvidia channels don't have torchvision at all.

**Comment by hmaarrfk** [comment]
Thank you for the MRC.

Do you have an example of an environment that has `torchvision=0.2.2=py_3` installed?

As mentionned above, we actually didn't really release anything on conda forge between 2.1 and 8.1. Therefore, it is unlikely that 2.2 was *ever* installed from conda-forge. We have guidelines [explicitly against](https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages) deletion of packages. So I think it is doubly unlikely that that you ever downloaded torchvision 2.2 from us.

![image](https://user-images.githubusercontent.com/90008/227370595-ad1654a2-95b7-4bf0-b116-7c17800393bd.png)

I suggest:

1. Trying to find the original environment and using `conda list --show-channel-urls` to list out the actual packages packages installed.  The channel from which it was installed should also be listed.
2. Loosening the constraint on torchvision 2.2. Do you really need it?

**Comment by hmaarrfk** [comment]
(PS. the screenshot above shows that we didn't maintain this feedstock for a long time between 2.1 and 8.1.....)

**Comment by skroon** [comment]
Thank you for the guidance @hmaarrfk - the original image shows the channel as pytorch, so I assume I will need to open a question at https://github.com/pytorch/vision .
